--------------------------------------------------------
--  File created - Wednesday-April-08-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table UHA_ROOM_SYNC
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."UHA_ROOM_SYNC" 
   (	"NAME" VARCHAR2(50 BYTE), 
	"EMAIL_ADDRESS" VARCHAR2(50 BYTE), 
	"GENDER" VARCHAR2(50 BYTE), 
	"SMOKER" VARCHAR2(50 BYTE), 
	"NORE" VARCHAR2(50 BYTE), 
	"VEG_OR_NON_VEG" VARCHAR2(50 BYTE), 
	"STUDENT_ID" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into SYSTEM.UHA_ROOM_SYNC
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index UHA_ROOM_SYNC_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."UHA_ROOM_SYNC_PK" ON "SYSTEM"."UHA_ROOM_SYNC" ("STUDENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UHA_ROOM_SYNC_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYSTEM"."UHA_ROOM_SYNC_UK1" ON "SYSTEM"."UHA_ROOM_SYNC" ("EMAIL_ADDRESS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table UHA_ROOM_SYNC
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."UHA_ROOM_SYNC" MODIFY ("STUDENT_ID" NOT NULL ENABLE);
 
  ALTER TABLE "SYSTEM"."UHA_ROOM_SYNC" ADD CONSTRAINT "UHA_ROOM_SYNC_PK" PRIMARY KEY ("STUDENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "SYSTEM"."UHA_ROOM_SYNC" ADD CONSTRAINT "UHA_ROOM_SYNC_UK1" UNIQUE ("EMAIL_ADDRESS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table UHA_ROOM_SYNC
--------------------------------------------------------

  ALTER TABLE "SYSTEM"."UHA_ROOM_SYNC" ADD CONSTRAINT "UHA_ROOM_SYNC_FK1" FOREIGN KEY ("STUDENT_ID")
	  REFERENCES "SYSTEM"."UHA_STUDENT" ("STUDENT_ID") ENABLE;
