--------------------------------------------------------
--  DDL for Table UHA_ADMIN
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."UHA_ADMIN" 
   (	"STAFF_NO" VARCHAR2(50 BYTE), 
	"FIRST_NAME" VARCHAR2(50 BYTE), 
	"GENDER" VARCHAR2(1 BYTE), 
	"DOB" DATE, 
	"LOCATION" VARCHAR2(50 BYTE), 
	"POSITION" VARCHAR2(50 BYTE), 
	"LAST_NAME" VARCHAR2(50 BYTE), 
	"STREET" VARCHAR2(50 BYTE), 
	"CITY" VARCHAR2(20 BYTE), 
	"POSTCODE" NUMBER(6,0), 
	"COUNTRY" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UHA_ADMIN_ACTION_ON_LEASE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."UHA_ADMIN_ACTION_ON_LEASE" 
   (	"LEASE_NO" VARCHAR2(50 BYTE), 
	"STAFF_NO" VARCHAR2(50 BYTE), 
	"ACTION_TAKEN" VARCHAR2(20 BYTE), 
	"ACTION_DATE" DATE, 
	"COMMENTS" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UHA_ADMIN_ACTION_ON_PARKING
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."UHA_ADMIN_ACTION_ON_PARKING" 
   (	"PARKING_REQUEST_NO" VARCHAR2(50 BYTE), 
	"STAFF_NO" VARCHAR2(50 BYTE), 
	"ACTION_TAKEN" VARCHAR2(20 BYTE), 
	"ACTION_DATE" DATE, 
	"COMMENTS" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UHA_ADMIN_ACTION_ON_TICKET
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."UHA_ADMIN_ACTION_ON_TICKET" 
   (	"TICKET_NO" VARCHAR2(50 BYTE), 
	"STAFF_NO" VARCHAR2(50 BYTE), 
	"ACTION_TAKEN" VARCHAR2(20 BYTE), 
	"ACTION_DATETIME" TIMESTAMP (0), 
	"COMMENTS" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UHA_APARTMENT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."UHA_APARTMENT" 
   (	"APARTMENT_NO" VARCHAR2(50 BYTE), 
	"ADDRESS_ID" NUMBER, 
	"NO_OF_BEDS" NUMBER, 
	"NO_OF_BATHS" NUMBER, 
	"FRESHMEN_ALLOWED" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"ON_CAMPUS" VARCHAR2(1 BYTE), 
	"APARTMENT_TYPE" VARCHAR2(2 BYTE), 
	"SECURITY_DEPOSIT" NUMBER, 
	"STAFF_NO" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UHA_APPLICANT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."UHA_APPLICANT" 
   (	"APPLICANT_ID" VARCHAR2(50 BYTE), 
	"FIRST_NAME" VARCHAR2(50 BYTE), 
	"DOB" DATE, 
	"GENDER" VARCHAR2(1 BYTE), 
	"NATION_OF_ORIGIN" VARCHAR2(50 BYTE), 
	"SMOKER" VARCHAR2(1 BYTE), 
	"SPECIAL_NEEDS" VARCHAR2(50 BYTE) DEFAULT 'None', 
	"COMMENTS" VARCHAR2(50 BYTE) DEFAULT 'None', 
	"PHONE_NO" NUMBER(10,0), 
	"ALT_PHONE_NO" NUMBER(10,0), 
	"GUEST" VARCHAR2(1 BYTE), 
	"LAST_NAME" VARCHAR2(50 BYTE), 
	"STREET" VARCHAR2(50 BYTE), 
	"CITY" VARCHAR2(20 BYTE), 
	"POSTCODE" NUMBER(6,0), 
	"COUNTRY" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UHA_APPLICANT_FAMILY
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."UHA_APPLICANT_FAMILY" 
   (	"APPLICANT_ID" VARCHAR2(50 BYTE), 
	"RELATION" VARCHAR2(50 BYTE), 
	"DOB" DATE, 
	"FIRST_NAME" VARCHAR2(50 BYTE), 
	"LAST_NAME" VARCHAR2(50 BYTE), 
	"FAMILY_MEMBER_ID" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UHA_APPLICANT_NEXT_OF_KIN
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."UHA_APPLICANT_NEXT_OF_KIN" 
   (	"APPLICANT_ID" VARCHAR2(50 BYTE), 
	"RELATION" VARCHAR2(50 BYTE), 
	"PHONE_NO" NUMBER(12,0), 
	"STREET" VARCHAR2(50 BYTE), 
	"CITY" VARCHAR2(20 BYTE), 
	"POSTCODE" NUMBER(6,0), 
	"FIRST_NAME" VARCHAR2(50 BYTE), 
	"LAST_NAME" VARCHAR2(50 BYTE), 
	"NEXT_OF_KIN_ID" NUMBER, 
	"COUNTRY" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UHA_FAMILY_APARTMENT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."UHA_FAMILY_APARTMENT" 
   (	"APARTMENT_NO" VARCHAR2(50 BYTE), 
	"MONTHLY_RENT_RATE" NUMBER, 
	"NO_OF_BEDS" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UHA_GENERAL_BEDROOM_APARTMENT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."UHA_GENERAL_BEDROOM_APARTMENT" 
   (	"PLACE_NO" VARCHAR2(50 BYTE), 
	"ROOM_NO" VARCHAR2(20 BYTE), 
	"APARTMENT_NO" VARCHAR2(50 BYTE), 
	"MONTHLY_RENT_RATE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UHA_GUEST
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."UHA_GUEST" 
   (	"APPROVAL_ID" VARCHAR2(50 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"COACHING_COURSE" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UHA_HOUSING_ADDRESS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."UHA_HOUSING_ADDRESS" 
   (	"ADDRESS_ID" NUMBER, 
	"STREET" VARCHAR2(50 BYTE), 
	"CITY" VARCHAR2(50 BYTE), 
	"POSTCODE" NUMBER(5,0), 
	"HOUSING_NAME" VARCHAR2(50 BYTE), 
	"STATE" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UHA_HOUSING_NEAR_PARKING
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."UHA_HOUSING_NEAR_PARKING" 
   (	"LOT_NO" VARCHAR2(50 BYTE), 
	"ADDRESS_ID" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UHA_HOUSING_RESIDENCE_HALL
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."UHA_HOUSING_RESIDENCE_HALL" 
   (	"NAME" VARCHAR2(50 BYTE), 
	"ADDRESS_ID" NUMBER, 
	"PHONE_NO" NUMBER, 
	"STAFF_NO" VARCHAR2(50 BYTE), 
	"NO_OF_ROOMS" NUMBER, 
	"GRAD_UPPER_ONLY" VARCHAR2(1 BYTE), 
	"SECURITY_DEPOSIT" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UHA_INVOICE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."UHA_INVOICE" 
   (	"INVOICE_NO" VARCHAR2(50 BYTE), 
	"LEASE_NO" VARCHAR2(50 BYTE), 
	"APPLICANT_NO" VARCHAR2(50 BYTE), 
	"TYPE" VARCHAR2(20 BYTE), 
	"HOUSING_RENT" NUMBER(7,2), 
	"PARKING_RENT" NUMBER(7,2), 
	"PENALTY" NUMBER(7,2), 
	"DUE_DATE" DATE, 
	"DATE_PAID" DATE, 
	"METHOD_PAID" VARCHAR2(20 BYTE), 
	"STATUS" VARCHAR2(10 BYTE), 
	"TOTAL_FEES" NUMBER(7,2), 
	"DATE_BILLED" DATE, 
	"LATE" VARCHAR2(1 BYTE) DEFAULT 'N'
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UHA_LEASE
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."UHA_LEASE" 
   (	"LEASE_NO" VARCHAR2(50 BYTE), 
	"DURATION" NUMBER, 
	"APPLICANT_NO" VARCHAR2(50 BYTE), 
	"PLACE_NO" VARCHAR2(50 BYTE), 
	"ROOM_NO" VARCHAR2(20 BYTE), 
	"APARTMENT_NO" VARCHAR2(50 BYTE), 
	"ADDRESS_ID" NUMBER, 
	"SECURITY_DEPOSIT" NUMBER DEFAULT NULL, 
	"ENTER_DATE" DATE, 
	"LEAVE_DATE" DATE, 
	"PAYMENT_SCHEDULE_OPTION" VARCHAR2(10 BYTE) DEFAULT 'SEMESTERLY', 
	"REQUEST_STATUS" VARCHAR2(20 BYTE) DEFAULT 'PENDING', 
	"APARTMENT_TYPE" VARCHAR2(2 BYTE), 
	"TOTAL_RENT" NUMBER, 
	"REQUESTED_ON" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UHA_LEASE_REQUEST
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."UHA_LEASE_REQUEST" 
   (	"LEASE_NO" VARCHAR2(50 BYTE), 
	"PREFERENCE" NUMBER, 
	"APARTMENT_TYPE" VARCHAR2(2 BYTE), 
	"RESHALL_NAME" VARCHAR2(50 BYTE), 
	"APARTMENT_NO" VARCHAR2(50 BYTE), 
	"APPLICANT_NO" VARCHAR2(50 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UHA_LEASE_TERMINATION
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."UHA_LEASE_TERMINATION" 
   (	"TERMINATION_REQUEST_NO" VARCHAR2(50 BYTE), 
	"LEASE_NO" VARCHAR2(50 BYTE), 
	"REQUEST_STATUS" VARCHAR2(20 BYTE) DEFAULT 'PENDING', 
	"TERMINATION_DATE" DATE, 
	"INSPECTION_DATE" DATE, 
	"INSPECTION_COMMENTS" VARCHAR2(50 BYTE), 
	"FEES_LEVIED_ON_INSPECTION" NUMBER DEFAULT 0, 
	"TERMINATION_REASON" VARCHAR2(200 BYTE), 
	"EARLY_TERMINATION_FEES" NUMBER(6,2), 
	"DAYS_REMAINING_FEES" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UHA_PARKING_LOT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."UHA_PARKING_LOT" 
   (	"LOT_NO" VARCHAR2(50 BYTE), 
	"NO_OF_SPOTS" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UHA_PARKING_REQUEST
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."UHA_PARKING_REQUEST" 
   (	"PARKING_REQUEST_NO" VARCHAR2(50 BYTE), 
	"LEASE_NO" VARCHAR2(50 BYTE), 
	"APPLICANT_NO" VARCHAR2(50 BYTE), 
	"PERMIT_ID" VARCHAR2(50 BYTE), 
	"REQUEST_STATUS" VARCHAR2(20 BYTE) DEFAULT 'PENDING', 
	"VEHICLE_TYPE" VARCHAR2(20 BYTE), 
	"OTHER_CLASSIFICATION_ACCEPTED" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"NOT_NEAR_HOUSING_AREA_ACCEPTED" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"HANDICAPPED" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"SPOT_ID" VARCHAR2(50 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UHA_PARKING_SPOT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."UHA_PARKING_SPOT" 
   (	"SPOT_NO" VARCHAR2(50 BYTE), 
	"LOT_NO" VARCHAR2(50 BYTE), 
	"CLASSIFICATION" VARCHAR2(20 BYTE) DEFAULT NULL, 
	"MONTHLY_RENT" NUMBER, 
	"HANDICAPPED" VARCHAR2(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UHA_RESIDENCE_HALL_ROOM
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."UHA_RESIDENCE_HALL_ROOM" 
   (	"PLACE_NO" VARCHAR2(50 BYTE), 
	"RESIDENCE_HALL_NAME" VARCHAR2(50 BYTE), 
	"ROOM_NO" VARCHAR2(20 BYTE), 
	"MONTHLY_RENT_RATE" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UHA_STUDENT
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."UHA_STUDENT" 
   (	"STUDENT_ID" VARCHAR2(50 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"COURSE" VARCHAR2(50 BYTE), 
	"CATEGORY_YEAR" NUMBER, 
	"CATEGORY_DEGREE" VARCHAR2(2 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UHA_TICKET
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."UHA_TICKET" 
   (	"TICKET_NO" VARCHAR2(50 BYTE), 
	"TICKET_TYPE" VARCHAR2(50 BYTE), 
	"SEVERITY" VARCHAR2(20 BYTE), 
	"RAISED_BY" VARCHAR2(50 BYTE), 
	"RAISED_DATE" DATE, 
	"LOCATION" VARCHAR2(50 BYTE), 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'PENDING', 
	"PROCESSED_DATETIME" TIMESTAMP (6), 
	"SEVERITY_ID" NUMBER, 
	"TICKET_DESCRIPTION" VARCHAR2(200 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UHA_USERS
--------------------------------------------------------

  CREATE TABLE "SYSTEM"."UHA_USERS" 
   (	"USER_ID" VARCHAR2(50 BYTE), 
	"USER_TYPE" VARCHAR2(20 BYTE), 
	"APPLICANT_ID" VARCHAR2(50 BYTE), 
	"STAFF_NO" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
